### ISSUE TITLE
Complexity of JS files

### ISSUE THREAD

**Issue by vbjeronimo** [just1ngray/CSCI2356_AutismNS#22] opened 2020-03-05 23:41 UTC
I'm trying to implement the reviewMail() function into the project but I'm having a hard time trying to modify sendMail() to work together with reviewMail(). The issue is that sendMail() will now be called in a new HTML file I created called emailreview.html instead of compose.html, and reviewMail() will be called in compose.html. Because of this, from the new review window that opens, I can't access the stuff they typed into compose.html and so I need to modify sendMail().

But I don't know how to do it because the two files that deal with the emails are a kinda complex and I'm hesitant to change anything and mess up the whole thing. Can we simplify the code a little more? Maybe getting rid of the account part and having two separate JS files, one for each system as Terry suggested. I know it doesn't sound great, but I think we have too much code right now and the cleaner the code, the better for maintaining it and adding the backend.

What do you think? Also, if it's a lot of work to simplify everything, I can help with anything.

**Comment by just1ngray** [comment] 2020-03-06 02:49
Since Terry wants us to explain things, here goes!

**navigation.js**
- goTo(href): 
    1) Saves the current window.location.href to localstorage so we can go back once. 
    2) Sets the window.location.href to 'href' argument.
- goBack(): takes the user back to whatever was saved into localstorage as lastPage
- openHelp(id): opens a help window for whatever VALUE is found in the specified id (to, from, cc, subject, etc)

**io.js**
This file was created to manage all read/writing to localstorage that will later be controlled using the server.
- read(key): returns whatever value is in localstorage that matches the key
- write(key, value): sets localstorage key to value

Now, for the rest of the system we can store our information multiple ways.
1. adminInbox, adminSentMail, studentInbox, studentSentMail
2. (this is what we do): Store the JSON 'Account' object. An account is made up of:
        - name: student or admin string
        - inbox: array of emails
        - sentMail: array of emails
The advantage of #2: We only have to read/write one object per account to/from memory.

Either way, we need to have an Email object (JSON) to store all the data for an email.
- fakeFrom: the displayed from address (may not be admin or student)
- fakeTo: the displayed to address (may not be admin or student)
- cc: whatever cc address was entered
- subject: the subject of the mail
- body: the body of the message
- isRead: boolean T/F if the email has been read
- realFrom: student or admin (admin writes from admin, student writes from student)
- realTo: student or admin (admin writes to student, student writes to admin)
- date: the number of milliseconds (int?) since some date in 1970 (jan 1?)
- owner: duplicate of realFrom or realTo (to sentMail, owner is set as realFrom) (to an inbox, owner
    is set to realTo)
- isInbox: boolean (T/F) if the email is stored in an account's inbox

**accountManager.js**
- Account object as previously described
- saveAccounts(sender, recipient): saves both accounts assuming the proper inbox/sentMails have 
    space
- saveAccount(account): saves a single account
- getAccount(name): gets an account from our io.js script by key (name)

**emailManager.js**
- Email object as previously described
- displayEmails(id, emails, isInbox): displays the emails in a proper list dynamically
    id: the element in which to display the emails
    emails: the array of emails to display
    isInbox: if the emails are being displayed in an inbox
- sendMail(): sends an email from the compose.html page
    1. from: either student (if no from field is found - like on student system), or attained value from
        the from field in the admin account
    2. to, cc, subject, body: all taken from the input boxes
    3. create the email object
    4. add email to the proper account's boxes (inbox or sent mail)
    5. saveAccounts if there is room, otherwise alert error
- deleteMail(stringifiedEmail): deletes an email from a box
    stringifiedEmail: this one is confusing. But essentially it's:
        var stringMail = JSON.stringify(email);
        stringifiedEmail = escape(stringMail); // converts escape chars to % and stuff so it can be
            stored in plain text inside ".." without errors with escape chars (i.e. "\")
- viewMail(stringifiedEmail): sets the localstorage key displayEmail to JSON stringified email so it
    can be loaded in loadMail. Redirects to email.html
- loadMail(): runs when email.html loads. Fills in fields according to the email at key displayEmail

**Comment by just1ngray** [comment] 2020-03-06 02:56
Now, to address your question lol

Here's what you'd need to do to create an entire reviewEmail page:
1. compose.html send button links to a new method called 'review' or something
2. 'review' does:
    - sets localstorage emailToSend as the email (created just like in sendMail lines 92-104)
    - sets localstorage emailToRecieve as the email (created in sendMail lines 92-98, 107-110)
    - redirects to the new page reviewEmail
3. new page loads in data from emailToSend
4. cancel takes you back to the compose.html page
5. send saves the emailToSend to sender, and emailToRecieve to reciever and saves accounts

I'll create a branch 'emailReview' with the framework.

**Comment by just1ngray** [comment] 2020-03-06 03:16
Correction, branch is named emailReview2. Seems we had a similar naming idea!

**Comment by vbjeronimo** [comment] 2020-03-07 09:42
Thanks Justin, the instructions were very helpful. I've just created a Pull Request and I'm waiting for your review just to make sure that everything is ok indeed. I'm just having a small problem: after clicking confirm, the window closes and the user is not redirected to Sent Items. I have no idea how to solve this. The reason is that the review page is opening on another window and the code for the confirmation + sending the email is running on this new window, so it can't interact with compose.html that is open on the background. I will take another look tomorrow to see if I can find an answer.

**Comment by JayPatel200** [comment] 2020-03-07 17:07
I have created a function emailManager named confirmation(). Vitor, take a look if you can get a simpler way to make it work. But the above-discussed way sounds good too(makes code look simpler and organized).

**Comment by just1ngray** [comment] 2020-03-09 23:42
We good to close this?

**Closed as completed** 2020-03-10 01:03 UTC
Labels: help wanted
